/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface BEACON {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"BEACON\",\"namespace\":\"org.ga4gh\",\"types\":[{\"type\":\"record\",\"name\":\"BEACONRequest\",\"fields\":[{\"name\":\"populationId\",\"type\":[\"null\",\"string\"],\"doc\":\"The name of the targeted population\",\"default\":null},{\"name\":\"referenceVersion\",\"type\":[\"null\",\"string\"],\"doc\":\"The version of the reference\",\"default\":null},{\"name\":\"chromosome\",\"type\":[\"null\",\"string\"],\"doc\":\"The chromosome of the request\",\"default\":null},{\"name\":\"coordinate\",\"type\":[\"null\",\"long\"],\"doc\":\"0-based allele locus\",\"default\":null},{\"name\":\"allele\",\"type\":[\"null\",\"string\"],\"doc\":\"allele\",\"default\":null}]},{\"type\":\"record\",\"name\":\"BEACONResponse\",\"fields\":[{\"name\":\"exists\",\"type\":[\"null\",\"boolean\"],\"doc\":\"outcome of the existence test\",\"default\":null},{\"name\":\"frequency\",\"type\":[\"null\",\"long\"],\"doc\":\"allele frequency\",\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends BEACON {
    public static final org.apache.avro.Protocol PROTOCOL = org.ga4gh.BEACON.PROTOCOL;
  }
}