/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh;  
@SuppressWarnings("all")
/** This request maps to the body of `POST /variants/search` as JSON. */
@org.apache.avro.specific.AvroGenerated
public class GASearchVariantsRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GASearchVariantsRequest\",\"namespace\":\"org.ga4gh\",\"doc\":\"This request maps to the body of `POST /variants/search` as JSON.\",\"fields\":[{\"name\":\"variantSetIds\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"Required. The IDs of the variant sets to search over.\",\"default\":[]},{\"name\":\"variantName\",\"type\":[\"null\",\"string\"],\"doc\":\"Only return variants which have exactly this name.\",\"default\":null},{\"name\":\"callSetIds\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"Only return variant calls which belong to call sets with these IDs.\\n  Leaving this blank returns all variant calls.\",\"default\":[]},{\"name\":\"referenceName\",\"type\":\"string\",\"doc\":\"Required. Only return variants on this reference.\"},{\"name\":\"start\",\"type\":\"long\",\"doc\":\"Required. The beginning of the window (0-based, inclusive) for\\n  which overlapping variants should be returned.\\n  Genomic positions are non-negative integers less than reference length.\\n  Requests spanning the join of circular genomes are represented as\\n  two requests one on each side of the join (position 0).\"},{\"name\":\"end\",\"type\":\"long\",\"doc\":\"Required. The end of the window (0-based, exclusive) for which overlapping\\n  variants should be returned.\"},{\"name\":\"pageSize\",\"type\":[\"null\",\"int\"],\"doc\":\"Specifies the maximum number of results to return in a single page.\\n  If unspecified, a system default will be used.\",\"default\":null},{\"name\":\"pageToken\",\"type\":[\"null\",\"string\"],\"doc\":\"The continuation token, which is used to page through large result sets.\\n  To get the next page of results, set this parameter to the value of\\n  `nextPageToken` from the previous response.\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Required. The IDs of the variant sets to search over. */
  @Deprecated public java.util.List<java.lang.CharSequence> variantSetIds;
  /** Only return variants which have exactly this name. */
  @Deprecated public java.lang.CharSequence variantName;
  /** Only return variant calls which belong to call sets with these IDs.
  Leaving this blank returns all variant calls. */
  @Deprecated public java.util.List<java.lang.CharSequence> callSetIds;
  /** Required. Only return variants on this reference. */
  @Deprecated public java.lang.CharSequence referenceName;
  /** Required. The beginning of the window (0-based, inclusive) for
  which overlapping variants should be returned.
  Genomic positions are non-negative integers less than reference length.
  Requests spanning the join of circular genomes are represented as
  two requests one on each side of the join (position 0). */
  @Deprecated public long start;
  /** Required. The end of the window (0-based, exclusive) for which overlapping
  variants should be returned. */
  @Deprecated public long end;
  /** Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used. */
  @Deprecated public java.lang.Integer pageSize;
  /** The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response. */
  @Deprecated public java.lang.CharSequence pageToken;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GASearchVariantsRequest() {}

  /**
   * All-args constructor.
   */
  public GASearchVariantsRequest(java.util.List<java.lang.CharSequence> variantSetIds, java.lang.CharSequence variantName, java.util.List<java.lang.CharSequence> callSetIds, java.lang.CharSequence referenceName, java.lang.Long start, java.lang.Long end, java.lang.Integer pageSize, java.lang.CharSequence pageToken) {
    this.variantSetIds = variantSetIds;
    this.variantName = variantName;
    this.callSetIds = callSetIds;
    this.referenceName = referenceName;
    this.start = start;
    this.end = end;
    this.pageSize = pageSize;
    this.pageToken = pageToken;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return variantSetIds;
    case 1: return variantName;
    case 2: return callSetIds;
    case 3: return referenceName;
    case 4: return start;
    case 5: return end;
    case 6: return pageSize;
    case 7: return pageToken;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: variantSetIds = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: variantName = (java.lang.CharSequence)value$; break;
    case 2: callSetIds = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: referenceName = (java.lang.CharSequence)value$; break;
    case 4: start = (java.lang.Long)value$; break;
    case 5: end = (java.lang.Long)value$; break;
    case 6: pageSize = (java.lang.Integer)value$; break;
    case 7: pageToken = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'variantSetIds' field.
   * Required. The IDs of the variant sets to search over.   */
  public java.util.List<java.lang.CharSequence> getVariantSetIds() {
    return variantSetIds;
  }

  /**
   * Sets the value of the 'variantSetIds' field.
   * Required. The IDs of the variant sets to search over.   * @param value the value to set.
   */
  public void setVariantSetIds(java.util.List<java.lang.CharSequence> value) {
    this.variantSetIds = value;
  }

  /**
   * Gets the value of the 'variantName' field.
   * Only return variants which have exactly this name.   */
  public java.lang.CharSequence getVariantName() {
    return variantName;
  }

  /**
   * Sets the value of the 'variantName' field.
   * Only return variants which have exactly this name.   * @param value the value to set.
   */
  public void setVariantName(java.lang.CharSequence value) {
    this.variantName = value;
  }

  /**
   * Gets the value of the 'callSetIds' field.
   * Only return variant calls which belong to call sets with these IDs.
  Leaving this blank returns all variant calls.   */
  public java.util.List<java.lang.CharSequence> getCallSetIds() {
    return callSetIds;
  }

  /**
   * Sets the value of the 'callSetIds' field.
   * Only return variant calls which belong to call sets with these IDs.
  Leaving this blank returns all variant calls.   * @param value the value to set.
   */
  public void setCallSetIds(java.util.List<java.lang.CharSequence> value) {
    this.callSetIds = value;
  }

  /**
   * Gets the value of the 'referenceName' field.
   * Required. Only return variants on this reference.   */
  public java.lang.CharSequence getReferenceName() {
    return referenceName;
  }

  /**
   * Sets the value of the 'referenceName' field.
   * Required. Only return variants on this reference.   * @param value the value to set.
   */
  public void setReferenceName(java.lang.CharSequence value) {
    this.referenceName = value;
  }

  /**
   * Gets the value of the 'start' field.
   * Required. The beginning of the window (0-based, inclusive) for
  which overlapping variants should be returned.
  Genomic positions are non-negative integers less than reference length.
  Requests spanning the join of circular genomes are represented as
  two requests one on each side of the join (position 0).   */
  public java.lang.Long getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * Required. The beginning of the window (0-based, inclusive) for
  which overlapping variants should be returned.
  Genomic positions are non-negative integers less than reference length.
  Requests spanning the join of circular genomes are represented as
  two requests one on each side of the join (position 0).   * @param value the value to set.
   */
  public void setStart(java.lang.Long value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'end' field.
   * Required. The end of the window (0-based, exclusive) for which overlapping
  variants should be returned.   */
  public java.lang.Long getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * Required. The end of the window (0-based, exclusive) for which overlapping
  variants should be returned.   * @param value the value to set.
   */
  public void setEnd(java.lang.Long value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   */
  public java.lang.Integer getPageSize() {
    return pageSize;
  }

  /**
   * Sets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   * @param value the value to set.
   */
  public void setPageSize(java.lang.Integer value) {
    this.pageSize = value;
  }

  /**
   * Gets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   */
  public java.lang.CharSequence getPageToken() {
    return pageToken;
  }

  /**
   * Sets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   * @param value the value to set.
   */
  public void setPageToken(java.lang.CharSequence value) {
    this.pageToken = value;
  }

  /** Creates a new GASearchVariantsRequest RecordBuilder */
  public static org.ga4gh.GASearchVariantsRequest.Builder newBuilder() {
    return new org.ga4gh.GASearchVariantsRequest.Builder();
  }
  
  /** Creates a new GASearchVariantsRequest RecordBuilder by copying an existing Builder */
  public static org.ga4gh.GASearchVariantsRequest.Builder newBuilder(org.ga4gh.GASearchVariantsRequest.Builder other) {
    return new org.ga4gh.GASearchVariantsRequest.Builder(other);
  }
  
  /** Creates a new GASearchVariantsRequest RecordBuilder by copying an existing GASearchVariantsRequest instance */
  public static org.ga4gh.GASearchVariantsRequest.Builder newBuilder(org.ga4gh.GASearchVariantsRequest other) {
    return new org.ga4gh.GASearchVariantsRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for GASearchVariantsRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GASearchVariantsRequest>
    implements org.apache.avro.data.RecordBuilder<GASearchVariantsRequest> {

    private java.util.List<java.lang.CharSequence> variantSetIds;
    private java.lang.CharSequence variantName;
    private java.util.List<java.lang.CharSequence> callSetIds;
    private java.lang.CharSequence referenceName;
    private long start;
    private long end;
    private java.lang.Integer pageSize;
    private java.lang.CharSequence pageToken;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.GASearchVariantsRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.GASearchVariantsRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.variantSetIds)) {
        this.variantSetIds = data().deepCopy(fields()[0].schema(), other.variantSetIds);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.variantName)) {
        this.variantName = data().deepCopy(fields()[1].schema(), other.variantName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.callSetIds)) {
        this.callSetIds = data().deepCopy(fields()[2].schema(), other.callSetIds);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.referenceName)) {
        this.referenceName = data().deepCopy(fields()[3].schema(), other.referenceName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.start)) {
        this.start = data().deepCopy(fields()[4].schema(), other.start);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.end)) {
        this.end = data().deepCopy(fields()[5].schema(), other.end);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[6].schema(), other.pageSize);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[7].schema(), other.pageToken);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GASearchVariantsRequest instance */
    private Builder(org.ga4gh.GASearchVariantsRequest other) {
            super(org.ga4gh.GASearchVariantsRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.variantSetIds)) {
        this.variantSetIds = data().deepCopy(fields()[0].schema(), other.variantSetIds);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.variantName)) {
        this.variantName = data().deepCopy(fields()[1].schema(), other.variantName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.callSetIds)) {
        this.callSetIds = data().deepCopy(fields()[2].schema(), other.callSetIds);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.referenceName)) {
        this.referenceName = data().deepCopy(fields()[3].schema(), other.referenceName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.start)) {
        this.start = data().deepCopy(fields()[4].schema(), other.start);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.end)) {
        this.end = data().deepCopy(fields()[5].schema(), other.end);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[6].schema(), other.pageSize);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[7].schema(), other.pageToken);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'variantSetIds' field */
    public java.util.List<java.lang.CharSequence> getVariantSetIds() {
      return variantSetIds;
    }
    
    /** Sets the value of the 'variantSetIds' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setVariantSetIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.variantSetIds = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'variantSetIds' field has been set */
    public boolean hasVariantSetIds() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'variantSetIds' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearVariantSetIds() {
      variantSetIds = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'variantName' field */
    public java.lang.CharSequence getVariantName() {
      return variantName;
    }
    
    /** Sets the value of the 'variantName' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setVariantName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.variantName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'variantName' field has been set */
    public boolean hasVariantName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'variantName' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearVariantName() {
      variantName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'callSetIds' field */
    public java.util.List<java.lang.CharSequence> getCallSetIds() {
      return callSetIds;
    }
    
    /** Sets the value of the 'callSetIds' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setCallSetIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.callSetIds = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'callSetIds' field has been set */
    public boolean hasCallSetIds() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'callSetIds' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearCallSetIds() {
      callSetIds = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'referenceName' field */
    public java.lang.CharSequence getReferenceName() {
      return referenceName;
    }
    
    /** Sets the value of the 'referenceName' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setReferenceName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.referenceName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'referenceName' field has been set */
    public boolean hasReferenceName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'referenceName' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearReferenceName() {
      referenceName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'start' field */
    public java.lang.Long getStart() {
      return start;
    }
    
    /** Sets the value of the 'start' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setStart(long value) {
      validate(fields()[4], value);
      this.start = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'start' field has been set */
    public boolean hasStart() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'start' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearStart() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'end' field */
    public java.lang.Long getEnd() {
      return end;
    }
    
    /** Sets the value of the 'end' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setEnd(long value) {
      validate(fields()[5], value);
      this.end = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'end' field has been set */
    public boolean hasEnd() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'end' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearEnd() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'pageSize' field */
    public java.lang.Integer getPageSize() {
      return pageSize;
    }
    
    /** Sets the value of the 'pageSize' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setPageSize(java.lang.Integer value) {
      validate(fields()[6], value);
      this.pageSize = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'pageSize' field has been set */
    public boolean hasPageSize() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'pageSize' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearPageSize() {
      pageSize = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'pageToken' field */
    public java.lang.CharSequence getPageToken() {
      return pageToken;
    }
    
    /** Sets the value of the 'pageToken' field */
    public org.ga4gh.GASearchVariantsRequest.Builder setPageToken(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.pageToken = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'pageToken' field has been set */
    public boolean hasPageToken() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'pageToken' field */
    public org.ga4gh.GASearchVariantsRequest.Builder clearPageToken() {
      pageToken = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public GASearchVariantsRequest build() {
      try {
        GASearchVariantsRequest record = new GASearchVariantsRequest();
        record.variantSetIds = fieldSetFlags()[0] ? this.variantSetIds : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.variantName = fieldSetFlags()[1] ? this.variantName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.callSetIds = fieldSetFlags()[2] ? this.callSetIds : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.referenceName = fieldSetFlags()[3] ? this.referenceName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.start = fieldSetFlags()[4] ? this.start : (java.lang.Long) defaultValue(fields()[4]);
        record.end = fieldSetFlags()[5] ? this.end : (java.lang.Long) defaultValue(fields()[5]);
        record.pageSize = fieldSetFlags()[6] ? this.pageSize : (java.lang.Integer) defaultValue(fields()[6]);
        record.pageToken = fieldSetFlags()[7] ? this.pageToken : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
