/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh;  
@SuppressWarnings("all")
/** An enum that represents biological sex.
TODO: This is moving to common in https://github.com/ga4gh/schemas/pull/138
and should be removed from this file. */
@org.apache.avro.specific.AvroGenerated
public enum GASex { 
  FEMALE, MALE, MIXED, BISEX, ASEX  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GASex\",\"namespace\":\"org.ga4gh\",\"doc\":\"An enum that represents biological sex.\\nTODO: This is moving to common in https://github.com/ga4gh/schemas/pull/138\\nand should be removed from this file.\",\"symbols\":[\"FEMALE\",\"MALE\",\"MIXED\",\"BISEX\",\"ASEX\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
