/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.wip;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GAAllele extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GAAllele\",\"namespace\":\"org.ga4gh.wip\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"sequence\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"GASegment\",\"doc\":\"*******************************************************************\",\"fields\":[{\"name\":\"variantId\",\"type\":\"string\"},{\"name\":\"start\",\"type\":\"int\"},{\"name\":\"end\",\"type\":\"int\"},{\"name\":\"side\",\"type\":{\"type\":\"enum\",\"name\":\"GAVariantSide\",\"symbols\":[\"PLUS\",\"MINUS\"]}},{\"name\":\"length\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.util.List<org.ga4gh.wip.GASegment> sequence;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GAAllele() {}

  /**
   * All-args constructor.
   */
  public GAAllele(java.lang.CharSequence id, java.util.List<org.ga4gh.wip.GASegment> sequence) {
    this.id = id;
    this.sequence = sequence;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sequence;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: sequence = (java.util.List<org.ga4gh.wip.GASegment>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sequence' field.
   */
  public java.util.List<org.ga4gh.wip.GASegment> getSequence() {
    return sequence;
  }

  /**
   * Sets the value of the 'sequence' field.
   * @param value the value to set.
   */
  public void setSequence(java.util.List<org.ga4gh.wip.GASegment> value) {
    this.sequence = value;
  }

  /** Creates a new GAAllele RecordBuilder */
  public static org.ga4gh.wip.GAAllele.Builder newBuilder() {
    return new org.ga4gh.wip.GAAllele.Builder();
  }
  
  /** Creates a new GAAllele RecordBuilder by copying an existing Builder */
  public static org.ga4gh.wip.GAAllele.Builder newBuilder(org.ga4gh.wip.GAAllele.Builder other) {
    return new org.ga4gh.wip.GAAllele.Builder(other);
  }
  
  /** Creates a new GAAllele RecordBuilder by copying an existing GAAllele instance */
  public static org.ga4gh.wip.GAAllele.Builder newBuilder(org.ga4gh.wip.GAAllele other) {
    return new org.ga4gh.wip.GAAllele.Builder(other);
  }
  
  /**
   * RecordBuilder for GAAllele instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GAAllele>
    implements org.apache.avro.data.RecordBuilder<GAAllele> {

    private java.lang.CharSequence id;
    private java.util.List<org.ga4gh.wip.GASegment> sequence;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.wip.GAAllele.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.wip.GAAllele.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sequence)) {
        this.sequence = data().deepCopy(fields()[1].schema(), other.sequence);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GAAllele instance */
    private Builder(org.ga4gh.wip.GAAllele other) {
            super(org.ga4gh.wip.GAAllele.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sequence)) {
        this.sequence = data().deepCopy(fields()[1].schema(), other.sequence);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.ga4gh.wip.GAAllele.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.ga4gh.wip.GAAllele.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'sequence' field */
    public java.util.List<org.ga4gh.wip.GASegment> getSequence() {
      return sequence;
    }
    
    /** Sets the value of the 'sequence' field */
    public org.ga4gh.wip.GAAllele.Builder setSequence(java.util.List<org.ga4gh.wip.GASegment> value) {
      validate(fields()[1], value);
      this.sequence = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'sequence' field has been set */
    public boolean hasSequence() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'sequence' field */
    public org.ga4gh.wip.GAAllele.Builder clearSequence() {
      sequence = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public GAAllele build() {
      try {
        GAAllele record = new GAAllele();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sequence = fieldSetFlags()[1] ? this.sequence : (java.util.List<org.ga4gh.wip.GASegment>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
