/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.wip;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum GACallSetType { 
  GENOTYPE, HAPLOTYPE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GACallSetType\",\"namespace\":\"org.ga4gh.wip\",\"symbols\":[\"GENOTYPE\",\"HAPLOTYPE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
