/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.wip;  
@SuppressWarnings("all")
/** ******************************************************************* */
@org.apache.avro.specific.AvroGenerated
public class GASegment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GASegment\",\"namespace\":\"org.ga4gh.wip\",\"doc\":\"*******************************************************************\",\"fields\":[{\"name\":\"variantId\",\"type\":\"string\"},{\"name\":\"start\",\"type\":\"int\"},{\"name\":\"end\",\"type\":\"int\"},{\"name\":\"side\",\"type\":{\"type\":\"enum\",\"name\":\"GAVariantSide\",\"symbols\":[\"PLUS\",\"MINUS\"]}},{\"name\":\"length\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence variantId;
  @Deprecated public int start;
  @Deprecated public int end;
  @Deprecated public org.ga4gh.wip.GAVariantSide side;
  @Deprecated public int length;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GASegment() {}

  /**
   * All-args constructor.
   */
  public GASegment(java.lang.CharSequence variantId, java.lang.Integer start, java.lang.Integer end, org.ga4gh.wip.GAVariantSide side, java.lang.Integer length) {
    this.variantId = variantId;
    this.start = start;
    this.end = end;
    this.side = side;
    this.length = length;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return variantId;
    case 1: return start;
    case 2: return end;
    case 3: return side;
    case 4: return length;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: variantId = (java.lang.CharSequence)value$; break;
    case 1: start = (java.lang.Integer)value$; break;
    case 2: end = (java.lang.Integer)value$; break;
    case 3: side = (org.ga4gh.wip.GAVariantSide)value$; break;
    case 4: length = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'variantId' field.
   */
  public java.lang.CharSequence getVariantId() {
    return variantId;
  }

  /**
   * Sets the value of the 'variantId' field.
   * @param value the value to set.
   */
  public void setVariantId(java.lang.CharSequence value) {
    this.variantId = value;
  }

  /**
   * Gets the value of the 'start' field.
   */
  public java.lang.Integer getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(java.lang.Integer value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'end' field.
   */
  public java.lang.Integer getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * @param value the value to set.
   */
  public void setEnd(java.lang.Integer value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'side' field.
   */
  public org.ga4gh.wip.GAVariantSide getSide() {
    return side;
  }

  /**
   * Sets the value of the 'side' field.
   * @param value the value to set.
   */
  public void setSide(org.ga4gh.wip.GAVariantSide value) {
    this.side = value;
  }

  /**
   * Gets the value of the 'length' field.
   */
  public java.lang.Integer getLength() {
    return length;
  }

  /**
   * Sets the value of the 'length' field.
   * @param value the value to set.
   */
  public void setLength(java.lang.Integer value) {
    this.length = value;
  }

  /** Creates a new GASegment RecordBuilder */
  public static org.ga4gh.wip.GASegment.Builder newBuilder() {
    return new org.ga4gh.wip.GASegment.Builder();
  }
  
  /** Creates a new GASegment RecordBuilder by copying an existing Builder */
  public static org.ga4gh.wip.GASegment.Builder newBuilder(org.ga4gh.wip.GASegment.Builder other) {
    return new org.ga4gh.wip.GASegment.Builder(other);
  }
  
  /** Creates a new GASegment RecordBuilder by copying an existing GASegment instance */
  public static org.ga4gh.wip.GASegment.Builder newBuilder(org.ga4gh.wip.GASegment other) {
    return new org.ga4gh.wip.GASegment.Builder(other);
  }
  
  /**
   * RecordBuilder for GASegment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GASegment>
    implements org.apache.avro.data.RecordBuilder<GASegment> {

    private java.lang.CharSequence variantId;
    private int start;
    private int end;
    private org.ga4gh.wip.GAVariantSide side;
    private int length;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.wip.GASegment.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.wip.GASegment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.variantId)) {
        this.variantId = data().deepCopy(fields()[0].schema(), other.variantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.end)) {
        this.end = data().deepCopy(fields()[2].schema(), other.end);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.side)) {
        this.side = data().deepCopy(fields()[3].schema(), other.side);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.length)) {
        this.length = data().deepCopy(fields()[4].schema(), other.length);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GASegment instance */
    private Builder(org.ga4gh.wip.GASegment other) {
            super(org.ga4gh.wip.GASegment.SCHEMA$);
      if (isValidValue(fields()[0], other.variantId)) {
        this.variantId = data().deepCopy(fields()[0].schema(), other.variantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.end)) {
        this.end = data().deepCopy(fields()[2].schema(), other.end);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.side)) {
        this.side = data().deepCopy(fields()[3].schema(), other.side);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.length)) {
        this.length = data().deepCopy(fields()[4].schema(), other.length);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'variantId' field */
    public java.lang.CharSequence getVariantId() {
      return variantId;
    }
    
    /** Sets the value of the 'variantId' field */
    public org.ga4gh.wip.GASegment.Builder setVariantId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.variantId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'variantId' field has been set */
    public boolean hasVariantId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'variantId' field */
    public org.ga4gh.wip.GASegment.Builder clearVariantId() {
      variantId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'start' field */
    public java.lang.Integer getStart() {
      return start;
    }
    
    /** Sets the value of the 'start' field */
    public org.ga4gh.wip.GASegment.Builder setStart(int value) {
      validate(fields()[1], value);
      this.start = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'start' field has been set */
    public boolean hasStart() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'start' field */
    public org.ga4gh.wip.GASegment.Builder clearStart() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'end' field */
    public java.lang.Integer getEnd() {
      return end;
    }
    
    /** Sets the value of the 'end' field */
    public org.ga4gh.wip.GASegment.Builder setEnd(int value) {
      validate(fields()[2], value);
      this.end = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'end' field has been set */
    public boolean hasEnd() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'end' field */
    public org.ga4gh.wip.GASegment.Builder clearEnd() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'side' field */
    public org.ga4gh.wip.GAVariantSide getSide() {
      return side;
    }
    
    /** Sets the value of the 'side' field */
    public org.ga4gh.wip.GASegment.Builder setSide(org.ga4gh.wip.GAVariantSide value) {
      validate(fields()[3], value);
      this.side = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'side' field has been set */
    public boolean hasSide() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'side' field */
    public org.ga4gh.wip.GASegment.Builder clearSide() {
      side = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'length' field */
    public java.lang.Integer getLength() {
      return length;
    }
    
    /** Sets the value of the 'length' field */
    public org.ga4gh.wip.GASegment.Builder setLength(int value) {
      validate(fields()[4], value);
      this.length = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'length' field has been set */
    public boolean hasLength() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'length' field */
    public org.ga4gh.wip.GASegment.Builder clearLength() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public GASegment build() {
      try {
        GASegment record = new GASegment();
        record.variantId = fieldSetFlags()[0] ? this.variantId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.start = fieldSetFlags()[1] ? this.start : (java.lang.Integer) defaultValue(fields()[1]);
        record.end = fieldSetFlags()[2] ? this.end : (java.lang.Integer) defaultValue(fields()[2]);
        record.side = fieldSetFlags()[3] ? this.side : (org.ga4gh.wip.GAVariantSide) defaultValue(fields()[3]);
        record.length = fieldSetFlags()[4] ? this.length : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
